create table if not exists public.grupos_contas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null check (char_length(btrim(nome)) between 1 and 40),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists grupos_contas_user_nome_uidx
  on public.grupos_contas (user_id, lower(btrim(nome)));
create index if not exists grupos_contas_user_idx on public.grupos_contas(user_id);

alter table public.contas_fixas
  add column if not exists grupo_id bigint references public.grupos_contas(id) on delete set null;
create index if not exists contas_fixas_user_grupo_idx on public.contas_fixas(user_id, grupo_id);

create or replace function public.validar_grupo_conta_fixa()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.grupo_id is not null and not exists (
    select 1 from public.grupos_contas
    where id = new.grupo_id and user_id = new.user_id
  ) then
    raise exception 'O grupo selecionado não pertence a esta conta.' using errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists validar_grupo_conta_fixa on public.contas_fixas;
create trigger validar_grupo_conta_fixa
  before insert or update of grupo_id, user_id on public.contas_fixas
  for each row execute function public.validar_grupo_conta_fixa();

drop trigger if exists set_grupos_contas_updated_at on public.grupos_contas;
create trigger set_grupos_contas_updated_at
  before update on public.grupos_contas
  for each row execute function public.set_updated_at();

alter table public.grupos_contas enable row level security;

drop policy if exists "Usuários leem os próprios dados" on public.grupos_contas;
drop policy if exists "Usuários inserem os próprios dados" on public.grupos_contas;
drop policy if exists "Usuários atualizam os próprios dados" on public.grupos_contas;
drop policy if exists "Usuários excluem os próprios dados" on public.grupos_contas;

create policy "Usuários leem os próprios dados" on public.grupos_contas
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Usuários inserem os próprios dados" on public.grupos_contas
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Usuários atualizam os próprios dados" on public.grupos_contas
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Usuários excluem os próprios dados" on public.grupos_contas
  for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.grupos_contas to authenticated;
grant usage, select on sequence public.grupos_contas_id_seq to authenticated;

create or replace function public.limpar_meus_dados()
returns void
language plpgsql
set search_path = public
as $$
begin
  delete from public.lancamentos where user_id = auth.uid();
  delete from public.contas_fixas where user_id = auth.uid();
  delete from public.grupos_contas where user_id = auth.uid();
  delete from public.metas where user_id = auth.uid();
  delete from public.cartoes_parcelas where user_id = auth.uid();
  delete from public.orcamentos where user_id = auth.uid();
  delete from public.objetivos_financeiros where user_id = auth.uid();
end;
$$;

revoke all on function public.limpar_meus_dados() from public, anon;
grant execute on function public.limpar_meus_dados() to authenticated;
