-- Camada de planejamento: orçamentos por categoria e objetivos financeiros.

create table if not exists public.orcamentos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mes date not null,
  categoria text not null check (char_length(trim(categoria)) between 1 and 80),
  limite numeric(14,2) not null check (limite > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.objetivos_financeiros (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null check (char_length(trim(nome)) between 1 and 120),
  tipo text not null default 'objetivo' check (tipo in ('objetivo', 'reserva_emergencia')),
  valor_alvo numeric(14,2) not null check (valor_alvo > 0),
  valor_atual numeric(14,2) not null default 0 check (valor_atual >= 0),
  prazo date,
  status text not null default 'ativo' check (status in ('ativo', 'concluido', 'pausado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists orcamentos_user_mes_categoria_uidx
  on public.orcamentos (user_id, mes, lower(categoria));
create index if not exists orcamentos_user_mes_idx on public.orcamentos(user_id, mes);
create index if not exists objetivos_user_status_idx on public.objetivos_financeiros(user_id, status);

drop trigger if exists set_orcamentos_updated_at on public.orcamentos;
create trigger set_orcamentos_updated_at before update on public.orcamentos
for each row execute function public.set_updated_at();

drop trigger if exists set_objetivos_financeiros_updated_at on public.objetivos_financeiros;
create trigger set_objetivos_financeiros_updated_at before update on public.objetivos_financeiros
for each row execute function public.set_updated_at();

alter table public.orcamentos enable row level security;
alter table public.objetivos_financeiros enable row level security;

do $$
declare
  tabela text;
  politica record;
begin
  foreach tabela in array array['orcamentos', 'objetivos_financeiros']
  loop
    for politica in select policyname from pg_policies where schemaname = 'public' and tablename = tabela
    loop
      execute format('drop policy %I on public.%I', politica.policyname, tabela);
    end loop;
    execute format('create policy "Usuários leem os próprios dados" on public.%I for select to authenticated using ((select auth.uid()) = user_id)', tabela);
    execute format('create policy "Usuários inserem os próprios dados" on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)', tabela);
    execute format('create policy "Usuários atualizam os próprios dados" on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', tabela);
    execute format('create policy "Usuários excluem os próprios dados" on public.%I for delete to authenticated using ((select auth.uid()) = user_id)', tabela);
  end loop;
end;
$$;

revoke all on public.orcamentos, public.objetivos_financeiros from anon;
grant select, insert, update, delete on public.orcamentos, public.objetivos_financeiros to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.aportar_objetivo(p_objetivo_id bigint, p_valor numeric)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  objetivo public.objetivos_financeiros%rowtype;
  novo_valor numeric(14,2);
  novo_status text;
begin
  if p_valor <= 0 then raise exception 'O aporte deve ser maior que zero.'; end if;

  select * into objetivo from public.objetivos_financeiros
  where id = p_objetivo_id and user_id = auth.uid() for update;
  if not found then raise exception 'Objetivo não encontrado.'; end if;

  novo_valor := objetivo.valor_atual + p_valor;
  novo_status := case when novo_valor >= objetivo.valor_alvo then 'concluido' else 'ativo' end;
  update public.objetivos_financeiros set valor_atual = novo_valor, status = novo_status
  where id = objetivo.id and user_id = auth.uid();

  return jsonb_build_object('valor_atual', novo_valor, 'status', novo_status);
end;
$$;

create or replace function public.limpar_meus_dados()
returns void
language plpgsql
set search_path = public
as $$
begin
  delete from public.lancamentos where user_id = auth.uid();
  delete from public.contas_fixas where user_id = auth.uid();
  delete from public.metas where user_id = auth.uid();
  delete from public.cartoes_parcelas where user_id = auth.uid();
  delete from public.orcamentos where user_id = auth.uid();
  delete from public.objetivos_financeiros where user_id = auth.uid();
end;
$$;

revoke all on function public.aportar_objetivo(bigint, numeric) from public, anon;
revoke all on function public.limpar_meus_dados() from public, anon;
grant execute on function public.aportar_objetivo(bigint, numeric) to authenticated;
grant execute on function public.limpar_meus_dados() to authenticated;
