-- Notificações push de vencimento (contas fixas e faturas de cartão).
-- push_subscriptions guarda a inscrição Web Push do navegador; perfis ganha
-- a preferência de ativar/desativar e a antecedência escolhida. O envio de
-- verdade roda numa Edge Function separada (check-vencimentos), chamada de
-- fora duas vezes por dia — este banco só guarda o "o quê" e o "quando",
-- nunca dispara nada sozinho.

alter table public.perfis add column if not exists notificar_vencimentos boolean not null default false;
alter table public.perfis add column if not exists notificar_antecedencia_dias smallint not null default 3;

alter table public.perfis drop constraint if exists perfis_antecedencia_dias_check;
alter table public.perfis
  add constraint perfis_antecedencia_dias_check
  check (notificar_antecedencia_dias in (1, 3, 5));

grant select (notificar_vencimentos, notificar_antecedencia_dias) on public.perfis to authenticated;
grant update (notificar_vencimentos, notificar_antecedencia_dias) on public.perfis to authenticated;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);

-- Um mesmo navegador/aparelho pode ter mais de um perfil (conta) logando
-- notificações nele — por isso a chave única é (endpoint, user_id), não só
-- endpoint: cada perfil tem sua própria linha ligada à mesma inscrição do
-- navegador.
create unique index if not exists push_subscriptions_endpoint_user_uidx
  on public.push_subscriptions(endpoint, user_id);
create index if not exists push_subscriptions_endpoint_idx on public.push_subscriptions(endpoint);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id);

alter table public.push_subscriptions enable row level security;

drop policy if exists "Usuários leem os próprios dados" on public.push_subscriptions;
drop policy if exists "Usuários inserem os próprios dados" on public.push_subscriptions;
drop policy if exists "Usuários atualizam os próprios dados" on public.push_subscriptions;
drop policy if exists "Usuários excluem os próprios dados" on public.push_subscriptions;

create policy "Usuários leem os próprios dados" on public.push_subscriptions
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Usuários inserem os próprios dados" on public.push_subscriptions
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Usuários atualizam os próprios dados" on public.push_subscriptions
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Usuários excluem os próprios dados" on public.push_subscriptions
  for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant usage, select on sequence public.push_subscriptions_id_seq to authenticated;

-- "Limpar meus dados" (perfil) passa a também remover as inscrições de
-- notificação deste usuário.
create or replace function public.limpar_meus_dados()
returns void
language plpgsql
set search_path = public
as $$
begin
  delete from public.lancamentos where user_id = auth.uid();
  delete from public.contas_fixas where user_id = auth.uid();
  delete from public.grupos_contas where user_id = auth.uid();
  delete from public.metas where user_id = auth.uid();
  delete from public.cartoes_parcelas where user_id = auth.uid();
  delete from public.cartoes where user_id = auth.uid();
  delete from public.orcamentos where user_id = auth.uid();
  delete from public.objetivos_financeiros where user_id = auth.uid();
  delete from public.categorias where user_id = auth.uid();
  delete from public.push_subscriptions where user_id = auth.uid();
end;
$$;

revoke all on function public.limpar_meus_dados() from public, anon;
grant execute on function public.limpar_meus_dados() to authenticated;
