-- My Future Finances
-- Esquema completo, políticas RLS e operações transacionais.

create extension if not exists pgcrypto;

create table if not exists public.perfis (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null default '',
  avatar_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint perfis_user_id_key unique (user_id)
);

create table if not exists public.lancamentos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tipo text not null check (tipo in ('receita', 'despesa')),
  categoria text not null,
  descricao text not null,
  valor numeric(14,2) not null check (valor > 0),
  data date not null default current_date,
  origem text,
  origem_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contas_fixas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  valor numeric(14,2) not null check (valor > 0),
  vencimento date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.metas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mes date not null default date_trunc('month', current_date)::date,
  valor numeric(14,2) not null check (valor > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint metas_user_mes_key unique (user_id, mes)
);

create table if not exists public.cartoes_parcelas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  cartao_nome text not null,
  cartao_final text not null default '',
  descricao text not null,
  valor_total numeric(14,2) not null check (valor_total > 0),
  total_parcelas integer not null check (total_parcelas > 0),
  parcelas_pagas integer not null default 0 check (parcelas_pagas >= 0),
  data_primeira_parcela date not null,
  dia_vencimento integer not null check (dia_vencimento between 1 and 31),
  status text not null default 'ativo' check (status in ('ativo', 'quitado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cartoes_parcelas_quantidade_check check (parcelas_pagas <= total_parcelas)
);

-- Compatibilidade com tabelas criadas anteriormente pelo protótipo.
alter table public.perfis add column if not exists created_at timestamptz not null default now();
alter table public.perfis add column if not exists updated_at timestamptz not null default now();
alter table public.lancamentos add column if not exists origem text;
alter table public.lancamentos add column if not exists origem_id bigint;
alter table public.lancamentos add column if not exists created_at timestamptz not null default now();
alter table public.lancamentos add column if not exists updated_at timestamptz not null default now();
alter table public.contas_fixas add column if not exists created_at timestamptz not null default now();
alter table public.contas_fixas add column if not exists updated_at timestamptz not null default now();
alter table public.metas add column if not exists mes date;
update public.metas set mes = date_trunc('month', current_date)::date where mes is null;
alter table public.metas alter column mes set default date_trunc('month', current_date)::date;
alter table public.metas alter column mes set not null;
alter table public.metas add column if not exists created_at timestamptz not null default now();
alter table public.metas add column if not exists updated_at timestamptz not null default now();
alter table public.cartoes_parcelas add column if not exists created_at timestamptz not null default now();
alter table public.cartoes_parcelas add column if not exists updated_at timestamptz not null default now();

create unique index if not exists perfis_user_id_uidx on public.perfis(user_id);
create unique index if not exists metas_user_mes_uidx on public.metas(user_id, mes);
create index if not exists lancamentos_user_data_idx on public.lancamentos(user_id, data desc);
create index if not exists contas_fixas_user_vencimento_idx on public.contas_fixas(user_id, vencimento);
create index if not exists cartoes_parcelas_user_idx on public.cartoes_parcelas(user_id);
create index if not exists lancamentos_origem_idx on public.lancamentos(user_id, origem, origem_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  tabela text;
begin
  foreach tabela in array array['perfis', 'lancamentos', 'contas_fixas', 'metas', 'cartoes_parcelas']
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', tabela, tabela);
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      tabela,
      tabela
    );
  end loop;
end;
$$;

create or replace function public.criar_perfil_novo_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.perfis (user_id, nome)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'nome', ''), split_part(new.email, '@', 1))
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists criar_perfil_apos_cadastro on auth.users;
create trigger criar_perfil_apos_cadastro
after insert on auth.users
for each row execute function public.criar_perfil_novo_usuario();

alter table public.perfis enable row level security;
alter table public.lancamentos enable row level security;
alter table public.contas_fixas enable row level security;
alter table public.metas enable row level security;
alter table public.cartoes_parcelas enable row level security;

do $$
declare
  tabela text;
  politica record;
begin
  foreach tabela in array array['perfis', 'lancamentos', 'contas_fixas', 'metas', 'cartoes_parcelas']
  loop
    for politica in
      select policyname
      from pg_policies
      where schemaname = 'public' and tablename = tabela
    loop
      execute format('drop policy %I on public.%I', politica.policyname, tabela);
    end loop;
    execute format(
      'create policy "Usuários leem os próprios dados" on public.%I for select to authenticated using ((select auth.uid()) = user_id)',
      tabela
    );
    execute format(
      'create policy "Usuários inserem os próprios dados" on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)',
      tabela
    );
    execute format(
      'create policy "Usuários atualizam os próprios dados" on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)',
      tabela
    );
    execute format(
      'create policy "Usuários excluem os próprios dados" on public.%I for delete to authenticated using ((select auth.uid()) = user_id)',
      tabela
    );
  end loop;
end;
$$;

revoke all on public.perfis, public.lancamentos, public.contas_fixas, public.metas, public.cartoes_parcelas from anon;
grant select, insert, update, delete on public.perfis, public.lancamentos, public.contas_fixas, public.metas, public.cartoes_parcelas to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.pagar_conta_fixa(p_conta_id bigint)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  conta public.contas_fixas%rowtype;
  novo_vencimento date;
begin
  select * into conta
  from public.contas_fixas
  where id = p_conta_id and user_id = auth.uid()
  for update;

  if not found then
    raise exception 'Conta fixa não encontrada.';
  end if;

  novo_vencimento := (conta.vencimento + interval '1 month')::date;

  insert into public.lancamentos (user_id, tipo, categoria, descricao, valor, data, origem, origem_id)
  values (auth.uid(), 'despesa', 'Conta fixa', conta.nome, conta.valor, current_date, 'conta_fixa', conta.id);

  update public.contas_fixas
  set vencimento = novo_vencimento
  where id = conta.id and user_id = auth.uid();

  return jsonb_build_object('vencimento', novo_vencimento);
end;
$$;

create or replace function public.pagar_parcela_cartao(p_parcelamento_id bigint)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  compra public.cartoes_parcelas%rowtype;
  novas_pagas integer;
  valor_parcela numeric(14,2);
  novo_status text;
begin
  select * into compra
  from public.cartoes_parcelas
  where id = p_parcelamento_id and user_id = auth.uid()
  for update;

  if not found then
    raise exception 'Parcelamento não encontrado.';
  end if;

  if compra.parcelas_pagas >= compra.total_parcelas then
    raise exception 'Este parcelamento já está quitado.';
  end if;

  novas_pagas := compra.parcelas_pagas + 1;
  valor_parcela := round(compra.valor_total / compra.total_parcelas, 2);
  novo_status := case when novas_pagas >= compra.total_parcelas then 'quitado' else 'ativo' end;

  insert into public.lancamentos (user_id, tipo, categoria, descricao, valor, data, origem, origem_id)
  values (
    auth.uid(),
    'despesa',
    'Cartão de crédito',
    format('%s - %s (%s/%s)', compra.cartao_nome, compra.descricao, novas_pagas, compra.total_parcelas),
    valor_parcela,
    current_date,
    'cartao',
    compra.id
  );

  update public.cartoes_parcelas
  set parcelas_pagas = novas_pagas, status = novo_status
  where id = compra.id and user_id = auth.uid();

  return jsonb_build_object('parcelas_pagas', novas_pagas, 'status', novo_status);
end;
$$;

create or replace function public.limpar_meus_dados()
returns void
language plpgsql
set search_path = public
as $$
begin
  delete from public.lancamentos where user_id = auth.uid();
  delete from public.contas_fixas where user_id = auth.uid();
  delete from public.metas where user_id = auth.uid();
  delete from public.cartoes_parcelas where user_id = auth.uid();
end;
$$;

create or replace function public.excluir_parcelamento_cartao(p_parcelamento_id bigint)
returns void
language plpgsql
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.cartoes_parcelas
    where id = p_parcelamento_id and user_id = auth.uid()
  ) then
    raise exception 'Parcelamento não encontrado.';
  end if;

  delete from public.lancamentos
  where user_id = auth.uid() and origem = 'cartao' and origem_id = p_parcelamento_id;

  delete from public.cartoes_parcelas
  where id = p_parcelamento_id and user_id = auth.uid();
end;
$$;

revoke all on function public.pagar_conta_fixa(bigint) from public, anon;
revoke all on function public.pagar_parcela_cartao(bigint) from public, anon;
revoke all on function public.limpar_meus_dados() from public, anon;
revoke all on function public.excluir_parcelamento_cartao(bigint) from public, anon;
grant execute on function public.pagar_conta_fixa(bigint) to authenticated;
grant execute on function public.pagar_parcela_cartao(bigint) to authenticated;
grant execute on function public.limpar_meus_dados() to authenticated;
grant execute on function public.excluir_parcelamento_cartao(bigint) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 2097152, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Avatares são públicos" on storage.objects;
drop policy if exists "Usuários enviam o próprio avatar" on storage.objects;
drop policy if exists "Usuários atualizam o próprio avatar" on storage.objects;
drop policy if exists "Usuários excluem o próprio avatar" on storage.objects;

create policy "Avatares são públicos"
on storage.objects for select
using (bucket_id = 'avatars');

create policy "Usuários enviam o próprio avatar"
on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Usuários atualizam o próprio avatar"
on storage.objects for update to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Usuários excluem o próprio avatar"
on storage.objects for delete to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
