-- Cartões cadastrados: cartão passa a ser uma entidade própria (nome, final,
-- dia de vencimento da fatura), reutilizável tanto pelas compras parceladas
-- quanto pelas contas fixas que são pagas no cartão em vez de em dinheiro.
-- Não altera nenhum cálculo existente do dashboard: contas fixas vinculadas
-- a um cartão continuam contando normalmente em "pendências" e no fluxo de
-- "marcar como paga"; o vínculo é só informativo/organizacional.

create table if not exists public.cartoes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null check (char_length(btrim(nome)) between 1 and 60),
  final text not null default '' check (final = '' or final ~ '^[0-9]{1,4}$'),
  dia_vencimento integer not null check (dia_vencimento between 1 and 31),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists cartoes_user_nome_uidx
  on public.cartoes (user_id, lower(btrim(nome)));
create index if not exists cartoes_user_idx on public.cartoes(user_id);

drop trigger if exists set_cartoes_updated_at on public.cartoes;
create trigger set_cartoes_updated_at
  before update on public.cartoes
  for each row execute function public.set_updated_at();

alter table public.cartoes enable row level security;

drop policy if exists "Usuários leem os próprios dados" on public.cartoes;
drop policy if exists "Usuários inserem os próprios dados" on public.cartoes;
drop policy if exists "Usuários atualizam os próprios dados" on public.cartoes;
drop policy if exists "Usuários excluem os próprios dados" on public.cartoes;

create policy "Usuários leem os próprios dados" on public.cartoes
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Usuários inserem os próprios dados" on public.cartoes
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Usuários atualizam os próprios dados" on public.cartoes
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Usuários excluem os próprios dados" on public.cartoes
  for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.cartoes to authenticated;
grant usage, select on sequence public.cartoes_id_seq to authenticated;

-- Vínculo opcional: uma conta fixa pode ser paga no cartão em vez de em
-- dinheiro (ex.: assinaturas de streaming). Ao excluir o cartão, a conta
-- continua existindo, apenas sem cartão vinculado.
alter table public.contas_fixas
  add column if not exists cartao_id bigint references public.cartoes(id) on delete set null;
create index if not exists contas_fixas_user_cartao_idx on public.contas_fixas(user_id, cartao_id);

-- Vínculo opcional: uma compra parcelada pode apontar para um cartão
-- cadastrado. cartao_nome/cartao_final continuam preenchidos (o app copia o
-- nome/final do cartão escolhido) para não quebrar nada que já lê essas
-- colunas diretamente.
alter table public.cartoes_parcelas
  add column if not exists cartao_id bigint references public.cartoes(id) on delete set null;
create index if not exists cartoes_parcelas_user_cartao_idx on public.cartoes_parcelas(user_id, cartao_id);

create or replace function public.validar_cartao_vinculado()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.cartao_id is not null and not exists (
    select 1 from public.cartoes
    where id = new.cartao_id and user_id = new.user_id
  ) then
    raise exception 'O cartão selecionado não pertence a este usuário.' using errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists validar_cartao_conta_fixa on public.contas_fixas;
create trigger validar_cartao_conta_fixa
  before insert or update of cartao_id, user_id on public.contas_fixas
  for each row execute function public.validar_cartao_vinculado();

drop trigger if exists validar_cartao_parcela on public.cartoes_parcelas;
create trigger validar_cartao_parcela
  before insert or update of cartao_id, user_id on public.cartoes_parcelas
  for each row execute function public.validar_cartao_vinculado();

-- Ao pagar uma conta fixa vinculada a um cartão, o lançamento gerado passa a
-- refletir isso (categoria "Cartão de crédito" e descrição com o nome do
-- cartão), em vez do genérico "Conta fixa". O restante do comportamento
-- (rolar o vencimento em +1 mês) continua idêntico ao de antes.
create or replace function public.pagar_conta_fixa(p_conta_id bigint)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  conta public.contas_fixas%rowtype;
  novo_vencimento date;
  nome_cartao text;
begin
  select * into conta
  from public.contas_fixas
  where id = p_conta_id and user_id = auth.uid()
  for update;

  if not found then
    raise exception 'Conta fixa não encontrada.';
  end if;

  novo_vencimento := (conta.vencimento + interval '1 month')::date;

  if conta.cartao_id is not null then
    select nome into nome_cartao from public.cartoes where id = conta.cartao_id and user_id = auth.uid();
  end if;

  insert into public.lancamentos (user_id, tipo, categoria, descricao, valor, data, origem, origem_id)
  values (
    auth.uid(),
    'despesa',
    case when nome_cartao is not null then 'Cartão de crédito' else 'Conta fixa' end,
    case when nome_cartao is not null then format('%s (%s)', conta.nome, nome_cartao) else conta.nome end,
    conta.valor,
    current_date,
    'conta_fixa',
    conta.id
  );

  update public.contas_fixas
  set vencimento = novo_vencimento
  where id = conta.id and user_id = auth.uid();

  return jsonb_build_object('vencimento', novo_vencimento);
end;
$$;

revoke all on function public.pagar_conta_fixa(bigint) from public, anon;
grant execute on function public.pagar_conta_fixa(bigint) to authenticated;

create or replace function public.limpar_meus_dados()
returns void
language plpgsql
set search_path = public
as $$
begin
  delete from public.lancamentos where user_id = auth.uid();
  delete from public.contas_fixas where user_id = auth.uid();
  delete from public.grupos_contas where user_id = auth.uid();
  delete from public.metas where user_id = auth.uid();
  delete from public.cartoes_parcelas where user_id = auth.uid();
  delete from public.cartoes where user_id = auth.uid();
  delete from public.orcamentos where user_id = auth.uid();
  delete from public.objetivos_financeiros where user_id = auth.uid();
end;
$$;

revoke all on function public.limpar_meus_dados() from public, anon;
grant execute on function public.limpar_meus_dados() to authenticated;
