-- Categorias personalizadas: o app já sugere uma lista básica (Alimentação,
-- Moradia, Transporte, Saúde, Educação, Lazer, Assinaturas, Salário,
-- Investimentos, Conta fixa, Cartão de crédito, Outros) direto no código, sem
-- precisar de linha nenhuma aqui. Esta tabela guarda só as categorias que
-- cada usuário adicionar por conta própria em "+ Nova categoria", na aba
-- Lançamentos. O campo "categoria" em lançamentos/orçamentos continua sendo
-- texto solto (não muda) — agora ele só passa a ser escolhido de uma lista
-- (as básicas + as personalizadas) em vez de digitado livremente.

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null check (char_length(btrim(nome)) between 1 and 40),
  created_at timestamptz not null default now()
);

create unique index if not exists categorias_user_nome_uidx
  on public.categorias (user_id, lower(btrim(nome)));
create index if not exists categorias_user_idx on public.categorias(user_id);

alter table public.categorias enable row level security;

drop policy if exists "Usuários leem os próprios dados" on public.categorias;
drop policy if exists "Usuários inserem os próprios dados" on public.categorias;
drop policy if exists "Usuários excluem os próprios dados" on public.categorias;

create policy "Usuários leem os próprios dados" on public.categorias
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Usuários inserem os próprios dados" on public.categorias
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Usuários excluem os próprios dados" on public.categorias
  for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, delete on public.categorias to authenticated;
grant usage, select on sequence public.categorias_id_seq to authenticated;

-- "Limpar meus dados" (se o usuário usar essa opção no perfil) passa a
-- também apagar as categorias personalizadas dele.
create or replace function public.limpar_meus_dados()
returns void
language plpgsql
set search_path = public
as $$
begin
  delete from public.lancamentos where user_id = auth.uid();
  delete from public.contas_fixas where user_id = auth.uid();
  delete from public.grupos_contas where user_id = auth.uid();
  delete from public.metas where user_id = auth.uid();
  delete from public.cartoes_parcelas where user_id = auth.uid();
  delete from public.cartoes where user_id = auth.uid();
  delete from public.orcamentos where user_id = auth.uid();
  delete from public.objetivos_financeiros where user_id = auth.uid();
  delete from public.categorias where user_id = auth.uid();
end;
$$;

revoke all on function public.limpar_meus_dados() from public, anon;
grant execute on function public.limpar_meus_dados() to authenticated;
